// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/auto/BaseIcon.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchDescription: typeof import('@headlessui/vue')['SwitchDescription']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
  }
}

export { }
